version: '2.6'

volumes:
  database-data:

services:
  database:
    image: postgres:14-alpine
    volumes:
      - database-data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
  api:
    build: ./api
    depends_on:
      - database
    restart: unless-stopped
    environment:
      - INITIAL_USER_EMAIL=$INITIAL_USER_EMAIL
      - INITIAL_USER_PASSWORD=$INITIAL_USER_PASSWORD
      - JWT_SECRET=$JWT_SECRET
      - PG_CONNECTION_STRING=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@database:5432/$POSTGRES_DB
  webapp:
    build: ./webapp
  http:
    image: nginx:1.22-alpine
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped