version: '2.6'
services:
  database:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
  api:
    build: ./api
    depends_on:
      - database
    environment:
      - INITIAL_USER_EMAIL=admin@example.com
      - INITIAL_USER_PASSWORD=12345678
      - JWT_SECRET=$JWT_SECRET
      - PG_CONNECTION_STRING=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@database:5432/$POSTGRES_DB
